# select and copy in vi style
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Escape send-keys -X cancel

bind C-l send-keys 'C-l' # clear screen with <prefix>-control-l

# idk why they are in reverse by default
bind 'h' split-window -v -c "#{pane_current_path}"
bind 'v' split-window -h -c "#{pane_current_path}"
