# window numbering lua style
set -g status-position top
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# set indicator colors
set -g @mode_indicator_prefix_mode_style 'bg=cyan,fg=black'
set -g @mode_indicator_copy_mode_style 'bg=yellow,fg=black'
set -g @mode_indicator_sync_mode_style 'bg=red,fg=black'
set -g @mode_indicator_empty_mode_style 'bg=blue,fg=black'

# set bar colors (probably can use terminal ones instead of hex)
set -g status-style "bg=#3b4252,fg=#d8dee9"
set -g window-status-format "#[fg=#d8dee9,bg=#434c5e]#W#{?#{==:#{window_index},#{last_window_index}}, ,}"
set -g window-status-current-format "#[fg=#d8dee9,bg=#434c5e]#W*#{?#{==:#{window_index},#{last_window_index}}, ,}"
set -g window-status-separator "#[bg=#434c5e] "
set -g status-left "#[fg=#2e3440,bg=#81a1c1] #S #[fg=#d8dee0,bg=#434c5e] "
set -g status-right "#{prefix_highlight}#[fg=#d8dee9,bg=#434c5e]#[fg=#d8dee9,bg=#434c5e,nobold,noitalics,nounderscore]#[fg=#d8dee9,bg=#434c5e] %H:%M #[fg=#2e3440,bg=#81a1c1]#{tmux_mode_indicator}"

# set pane border colors
set -g pane-border-style 'fg=#4c566a'
set -g pane-active-border-style 'fg=#80a1c1'

# set message colors
set -g message-style 'fg=#d8dee9,bg=#3b4252'
set -g message-command-style 'fg=#28dee9,bg=#3b4252'
