set -g default-terminal "tmux-256color"
set -s extended-keys on
set -a terminal-features "foot:RGB"
set -g pane-base-index 1
set -g base-index 1
set -g renumber-windows on
set -g mode-keys emacs
set -g status-keys emacs
set -g focus-events on
set -g status-position top
set -g status-left-length 99
set -g status-right-length 99
set -g status-justify absolute-centre

set -g pane-border-style "fg=#665c54"
set -g pane-active-border-style "fg=#b8bb26"
set -g status-style bg="#504945"

unbind C-w
set -g prefix C-w
bind C-w send-prefix

bind C-l send-keys C-l
bind s split-window -v -l 10
bind b last-window
bind q kill-pane

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -T copy-mode C-g send -X cancel
bind -T copy-mode C-Space \
    if-shell -F "#{selection_present}" \
    "send-keys -X clear-selection" \
    "send-keys -X begin-selection"

# locate previous prompt (it must end with ]$)
# change to other value if the prompt is different
bind-key -T copy-mode p send-keys -X search-backward-text "]$"
bind-key -T copy-mode n send-keys -X search-forward-text "]$"

bind-key -T copy-mode C-Space \
    if-shell -F "#{selection_present}" \
    "send-keys -X clear-selection" \
    "send-keys -X begin-selection"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
