export PATH="$PATH:$HOME/.local/bin"
export EDITOR="emacsclient -nw -a ''"
export VISUAL="emacsclient -c -a ''"
export PDFREADER="emacsclient -c -a ''"
export BROWSER="qutebrowser"
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
export PYTHON_HISTORY="$HOME/.local/share/python/history"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
