export PATH="$PATH:$HOME/.local/bin"
export EDITOR="emacsclient -t -a ''"
export VISUAL="emacsclient -r -a ''"
export PDFREADER="emacsclient -r -a ''"
export BROWSER="qutebrowser"
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
export PYTHON_HISTORY="$HOME/.local/share/python/history"
