#!/bin/sh

swaybg -i $(xdg-user-dir PICTURES)/wallpapers/the-ninth-wave-gruvbox.jpg >/dev/null 2>&1 &
mako >/dev/null 2>&1 &
emacs --daemon >/dev/null 2>&1 &
wl-paste --watch cliphist store &
ydotoold >/dev/null 2>&1 &
