exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle
exec-once = mako

# a hacky way to disable the startup animation
# exec = sleep 1 && hyprctl keyword animations:enabled true

exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
