# all "exec" and "exec-once" commands end up here
# documentation: https://wiki.hyprland.org/Configuring/Keywords

exec-once = waybar # bar
exec-once = hyprpaper # wallpaper
exec-once = hypridle # suspend on idle
exec-once = mako # notifications

# a hacky way to disable the startup animation
# exec = sleep 1 && hyprctl keyword animations:enabled true

# enable cliphist
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
