# all settings related to styling and animations end up here
# documentation: https://wiki.hyprland.org/Configuring/Animations

env = HYPRCURSOR_THEME,Nordzy-hyprcursors
env = HYPRCURSOR_SIZE,28
env = XCURSOR_SIZE,28

decoration {
	active_opacity = 1.0
	inactive_opacity = 1.0
	
	rounding = 5
	rounding_power = 4.0

	shadow {
		enabled=false
	}

	blur {
		enabled = false # change to true to enable blur
		special = false
		size = 14
		passes = 3
		brightness = 1
		noise = 0.01
		contrast = 1
		popups = true
		popups_ignorealpha = 0.6
		new_optimizations = true
		xray = true
	}
}

$speed = 3.2
animations {
    enabled = true
    bezier = myBezier, 0.05, 0.8, 0.1, 1.0

    animation = windows, 1, $speed, myBezier
    animation = windowsOut, 1, $speed, default, popin 80%
    animation = border, 1, $speed, default
    animation = borderangle, 1, $speed, default
    animation = fade, 1, 1.8, default
	animation = border, 0, 0, default
    animation = workspaces, 1, 2.5, default
    animation = specialWorkspace, 1, $speed, default, slidevert
}

