# all settings related to layouts end up here (except binds, for those look at binds.conf)
# documentation: https://wiki.hyprland.org/Configuring/Master-Layout

dwindle {
	pseudotile = true
	preserve_split = true
}

master {
	new_status = master
	new_on_top = true
}

