# all window and workspace rules end up here
# documentation: https://wiki.hyprland.org/Configuring/Window-Rules

# open some apps at dedicated workspaces
windowrulev2 = workspace 9, class:^(steam)$
windowrulev2 = noinitialfocus, class:^(steam)$
windowrulev2 = workspace 10, class:^(com.obsproject.Studio)$
windowrulev2 = workspace 2, class:^(org.telegram.desktop|telegramdesktop)$

# fix picture-in-picture in firefox
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = move 1906 14, title:(Picture-in-Picture)
windowrulev2 = float, title:^(Picture-in-Picture)$

# firefox history
windowrulev2 = float, class:^(firefox)$, title:^(Library)$

# resize the terminal popup with ranger
# check ~/.config/scripts/open_in_ranger.sh for more info
windowrule = float, title:^(ranger-popup)$
windowrule = size 800 500, title:^(ranger-popup)$

# resize pwvucontrol
windowrulev2 = float, class:^(com.saivert.pwvucontrol)$
windowrulev2 = size 800 500, class:^(com.saivert.pwvucontrol)$

# don't ask
windowrulev2 = stayfocused, class:^(photoshop.exe)$

# file manager
windowrulev2 = float, class:^(Pcmanfm)$

# file opener with xdg-desktop-portal-gtk
windowrulev2 = float, class:^(xdg-desktop-portal-gtk)$

# shrink terminal while floating
windowrulev2 = size 50% 40%, class:^(foot)$, floating:1
windowrulev2 = center, class:^(foot)$, floating:1

# enables smart gaps
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]

# defaults you probably shouldn't change
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# removes 1px border in hyprshot
layerrule = noanim, selection
