# dedicated workspaces for apps
windowrule = workspace 9, class:^(steam)$
windowrule = noinitialfocus, class:^(steam)$
windowrule = workspace 10, class:^(com.obsproject.Studio)$
windowrule = workspace 2, class:^(org.telegram.desktop|telegramdesktop)$

windowrule = pin, title:^(Picture-in-Picture)$
windowrule = move 1906 14, title:(Picture-in-Picture)
windowrule = float, title:^(Picture-in-Picture)$

# firefox history
windowrule = float, class:^(firefox)$, title:^(Library)$

# resize the terminal popup with ranger
# check ~/.config/scripts/open_in_ranger.sh for more info
windowrule = float, title:^(ranger-float)$
windowrule = size 800 500, title:^(ranger-float)$

windowrule = float, class:^(com.saivert.pwvucontrol)$
windowrule = size 800 500, class:^(com.saivert.pwvucontrol)$

windowrule = stayfocused, class:^(photoshop.exe)$

windowrule = size 50% 40%, class:^(foot)$, floating:1
windowrule = center, class:^(foot)$, floating:1

# removes 1px border in hyprshot
layerrule = noanim, selection

# enables smart gaps
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]

# defaults you probably shouldn't change
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

