source = ~/.config/hypr/hyprland/hardware.conf
source = ~/.config/hypr/hyprland/environment.conf
source = ~/.config/hypr/hyprland/binds.conf
source = ~/.config/hypr/hyprland/decorations.conf
source = ~/.config/hypr/hyprland/rules.conf
source = ~/.config/hypr/hyprland/autostart.conf
source = ~/.config/hypr/hyprland/layout.conf
source = ~/.config/hypr/hyprland/animations.conf

general {
	gaps_in = 5
	gaps_out = 60
	border_size = 1

	col.active_border = rgb(504945)
	col.inactive_border = rgb(504945)

	resize_on_border = false
	allow_tearing = false

	layout = master
}

misc {
	disable_hyprland_logo = true
	font_family = UbuntuMono Nerd Font
	background_color = rgb(1d2021)
}
