#  _
# | |_  _ _  ___  _ _ _/\_ a curated list of
# | . || | || . \| '_>>  < hypr* dotfiles
# |_|_|`_. ||  _/|_|   \/  made by yours truly
#      <___'|_|
#
# documentation: https://wiki.hyprland.org/Configuring
# dotfiles repo: https://github.com/ryazh3nka/.dotfiles

source = ~/.config/hypr/hyprland/hardware.conf
source = ~/.config/hypr/hyprland/binds.conf
source = ~/.config/hypr/hyprland/decorations.conf
source = ~/.config/hypr/hyprland/rules.conf
source = ~/.config/hypr/hyprland/autostart.conf
source = ~/.config/hypr/hyprland/layout.conf

general {
	gaps_in = 5
	gaps_out = 10
	border_size = 2
	
	col.active_border = rgb(80a1C1)
	#col.inactive_border = rgb(4c566a) 
	col.inactive_border = rgb(2e3440) 

	resize_on_border = false
	allow_tearing = false

	layout = master
}

misc {
	disable_hyprland_logo = true
	mouse_move_enables_dpms = true
	key_press_enables_dpms = true
	font_family = UbuntuMono Nerd Font
	background_color = rgb(2e3440)
}
