animations {
	enabled = true
	animation = fade, 1, 5, linear
}

background {
	monitor =
	
	path = ~/.config/wallpapers/pastel-sky.png
	vibrancy = 0.1696
	blur_passes = 3
	blur_size = 2
}

input-field {
	monitor =
	size = 200, 50

	font_family = Ubuntu
	font_size = 18
	font_color = rgb(d8dee9)

	halign = center
	valign = center
}
