#  _
# | |_  _ _  ___  _ _ _/\_ a curated list of
# | . || | || . \| '_>>  < hypr* dotfiles
# |_|_|`_. ||  _/|_|   \/  made by yours truly
#      <___'|_|
#
# documentation: https://wiki.hyprland.org/Hypr-Ecosystem/hyprpaper/
# dotfiles repo: https://github.com/ryazh3nka/.dotfiles

preload = ~/.config/wallpapers/pastel-sky.png
wallpaper = , ~/.config/wallpapers/pastel-sky.png
